# Experiment No :2

Review of python programming,matrix operations ,programs using matplotlib/plotly/bokeh/seaborn for data visualization and programs to handle data using pandas

In [24]:
import numpy as np
mat1=np.arange(1,10).reshape(3,3)
mat2=np.arange(11,20).reshape(3,3)
print("Matrix 1:\n",mat1)
print("Matrix 2:\n",mat2)
print("Sum of 2 matrices : \n",np.add(mat1,mat2))
print("Difference of 2 matrices : \n",np.subtract(mat2,mat1))
print("Product of 2 matrices : \n",np.dot(mat1,mat2))
print("Dividing the 2 matrices : \n",np.divide(mat2,mat1))
print("Transpose of matrix 1: \n",np.transpose(mat1))

Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Sum of 2 matrices : 
 [[12 14 16]
 [18 20 22]
 [24 26 28]]
Difference of 2 matrices : 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Product of 2 matrices : 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]
Dividing the 2 matrices : 
 [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
Transpose of matrix 1: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
